[workspace]
authors = ["Sam Holt <samjrholt@gmail.com>"]
channels = ["conda-forge"]
name = "BSW_data_generation"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
single-sim = "python generate_data.py"
collect-data = "python collect_data.py"

[dependencies]
python = "3.11.*"
jupyterlab = ">=4.5.3,<5"
esys-escript = ">=5.10,<6"
uppasd = ">=6.0.2,<7"
mammos = ">=0.11.2,<0.12"
tqdm = "*"

[pypi-dependencies]
jax = "==0.7.0"
jaxlib = "==0.7.0"
jax-cuda12-plugin = { version = "==0.7.0", extras = ["with-cuda"] }
jax-cuda12-pjrt = "==0.7.0"